name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build binaries
        run: ./build.sh

      - name: Prepare release assets
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          mkdir -p release
          
          # Copy universal launcher
          cp ecssh release/
          
          # Copy binaries directly (no archives)
          cp dist/ecssh-darwin-arm64 release/
          cp dist/ecssh-darwin-amd64 release/
          cp dist/ecssh-linux release/
          cp dist/ecssh-linux-arm64 release/
          cp dist/ecssh-windows.exe release/
          cp dist/ecssh-windows-arm64.exe release/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            release/ecssh
            release/ecssh-darwin-arm64
            release/ecssh-darwin-amd64
            release/ecssh-linux
            release/ecssh-linux-arm64
            release/ecssh-windows.exe
            release/ecssh-windows-arm64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}